### ISSUE TITLE
The 0007 south migration deletes the data column

### ISSUE THREAD

**Issue by drye** [django-notifications/django-notifications#46] opened 2015-03-19 20:11 UTC
In this commit f351e92223bdba05e8c71c4a6e16333ab69bb832 there's a south migration in which the data column gets deleted.

I'm pretty sure that breaks the arbitrary JSON data functionality and makes it potentially dangerous to upgrade.

**Comment by zhang-z** [comment] 2015-03-20 02:10
Thank you for pointing out my mistake.

I just checked the codes that related with "data" field (commit 55c4701):

    EXTRA_DATA = False
    if getattr(settings, 'NOTIFY_USE_JSONFIELD', False):
        try:
            from jsonfield.fields import JSONField
        except ImportError:
            raise ImproperlyConfigured("You must have a suitable JSONField installed")
        
        JSONField(blank=True, null=True).contribute_to_class(Notification, 'data')
        EXTRA_DATA = True

The "data" field was added to model dynamically. I wasn't aware that I should set `NOTIFY_USE_JSONFIELD=True`, when generating DB migration scripts. That's how the mistake came out.

I can commit a patch to add the "data" field back. But I'm thinking whether it's better to move definition of "data" field into model, regardless of the value of `NOTIFY_USE_JSONFIELD`. Because other people may make the same mistake in future. The drawback is "jsonfield" library then become as must for all users. What's your opinion?

**Comment by yangyubo** [comment] 2015-03-20 02:25
@zhang-z I think introduce "jsonfield" dependence is not a big deal. But you have the choice to decide how to handle this situation.

BTW, I have invited you as django-notifications maintainer, thanks a lot for responsive to your contribution.

**Comment by zhang-z** [comment] 2015-03-20 11:06
@yangyubo thank you for adding me into maintainers

@drye the issue is fixed in commit e244ba3

**Closed** 2015-03-20 11:06 UTC

**Comment by drye** [comment] 2015-03-20 21:08
Alright, thanks for the quick fix. :+1:
